version: '3.1'

services:
  app:
    build: '.'
    command: npm start
    container_name: app
    depends_on:
      - mysql-nwl3
    links:
      - mysql-nwl3
    volumes:
      - .:/usr/app
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - '3334:3334'

  mysql-nwl3:
    image: mysql:latest
    container_name: mysql-nwl3
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=happy
      - MYSQL_USER=natan
      - MYSQL_PASSWORD=natan12345
      - MYSQL_ROOT_PASSWORD=abc123
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app_network
    env_file:
      - .env

networks:
  app_network:

volumes:
  mysql_data:
