version: '3.1'

services:
  mysql-nwl3:
    image: mysql:latest
    container_name: mysql-nwl3
    environment:
      - MYSQL_DATABASE=happy
      - MYSQL_USER=natan
      - MYSQL_PASSWORD=natan12345
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_ROOT_HOST=%
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    networks:
      - app_network

  build:
    build: .
    image: app
    container_name: build
    command: dockerize -wait tcp://mysql-nwl3:3306 -timeout 60m npm run build
    volumes:
      - .:/home/node/api
    networks:
      - app_network
    depends_on:
      - mysql-nwl3

  # migration:
  #   build: .
  #   image: app
  #   container_name: migration
  #   command: dockerize -wait tcp://mysql-nwl3:3306 -timeout 60m npm run migrate
  #   volumes:
  #     - .:/home/node/api
  #     - /home/node/api/node_modules
  #   networks:
  #     - app_network
  #   depends_on:
  #     - mysql-nwl3

  app:
    build: .
    command: npm run start
    container_name: app
    depends_on:
      - mysql-nwl3
      - build
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - '3334:3334'

networks:
  app_network:
    driver: bridge
