version: "3.3"

services:
  mysql:
    image: mysql
    container_name: mysql-pi
    restart: always
    ports:
      - 3306:3306
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=pi
    volumes:
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data
  redis:
    image: 'bitnami/redis:latest'
    container_name: redis-pi
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=abc123


  app:
    build: .
    container_name: pi
    restart: always
    ports:
      - 3335:3335
    volumes:
      - .:/usr/app
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis



volumes:
  db-config:
    driver: local
  db-data:
    driver: local
