version: '3.1'

services:
  mysql-nwl3:
    image: mysql:latest
    container_name: mysql-nwl3
    environment:
      - MYSQL_DATABASE=happy
      - MYSQL_USER=natan
      - MYSQL_PASSWORD=natan12345
      - MYSQL_ROOT_PASSWORD=abc123
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    networks:
      - app_network

  # build:
  #   build: .
  #   container_name: build
  #   command: dockerize -wait tcp://mysql-nwl3:3306 -timeout 60m npm run build
  #   volumes:
  #     - .:/usr/app
  #   networks:
  #     - app_network
  #   depends_on:
  #     - mysql-nwl3

  migration:
    build: .
    container_name: migration
    command: dockerize -wait tcp://mysql-nwl3:3306 -timeout 60m npm run typeorm migration:run
    volumes:
      - .:/usr/app
    networks:
      - app_network
    depends_on:
      - mysql-nwl3

  app:
    build: .
    command: dockerize -wait tcp://mysql-nwl3:3306 -timeout 60m npm run dev
    container_name: app
    depends_on:
      - mysql-nwl3
    volumes:
      - .:/usr/app
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - '3334:3334'

networks:
  app_network:
    driver: bridge
